wechat_id: fengliu_buptsice
help_message: 您好，小菌菌正在建设中哦#^_^#
welcome_message:
  title: 欢迎亲关注风流
  picture: https://mp.weixin.qq.com/cgi-bin/getheadimg?fakeid=3080422015&token=1651482622&lang=zh_CN
  description: 欢迎亲关注风流~风流会推送杂志优秀文章和各种有趣的指南、冷知识给你哦~
  link: www.f4apps.com
